# -*- coding: utf-8 -*-
"""AI_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A8ee358yaOfg-o8vG_ACyGhrMoLqb_Ta
"""



"""# **List**"""

!pip install numpy

# Create a list of 10 integers
num =[1,2,3,4,5,6,7,8,9,10]
print('Original List: ', num)

#sum ,max and min
print('Max = ', max(num))
print('Min = ', min(num))
#print('Sum = ', sum(num))

# Add and Remove element
num.append(50)
num.remove(10)
print('Updated List: ', num)

#Sort ascending and decending
print('Ascending: ', sorted(num))
print('Descending: ', sorted(num, reverse=True))

"""# **Tuples**"""

#Create a tupple with strings
Fruits = ("Apple","Mango","Orange","Banana","peach")
print('Fruits :', Fruits)

#print 2nd and last index

print('2nd index :', Fruits[1])
print('Last index :', Fruits[-1])

#Try to modify an element then error or not
# Fruits.append("Grapes")
# print('Updated Fruits :', Fruits)
# Fruits.remove("Mango")
# print('Updated Fruits :', Fruits)

#convert the tupple into list
Fruits_list = list(Fruits)
Fruits_list.append("Grapes")
Fruits_list.remove("Mango")
print('Modified list :', Fruits_list)

"""# **Sets**"""

# Create two sets
A = {1, 2, 3, 4, 5,6,7}
B = {4, 5, 6, 7, 8,9,10}
print("Set A:", A)
print("Set B:", B)
# Union , Intersection , Differences of two sets
print("Union of A and B:", A | B)
print("Intersection of A and B:", A & B)
print("Difference of A and B:", A - B)
print("Difference of B and A:", B - A)

"""# **Dictionary**"""

#Create a keys of students

Friends = {'Hifza' : 90, 'Memoona ' : 89, 'Munazza ': 85, 'Alisha ': 87}

#print keys and values
print('Friends :', Friends)
print('Keys :', Friends.keys())
print('Values :', Friends.values())

#update value
# students['Hifza'] = 95
# print('Updated Friends :', Friends)

"""# **Numpy**

# **Matplotlib**
"""