# -*- coding: utf-8 -*-
"""first_AI Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b-MGoiLsubRTLSZGqwDRZw8qsAzVRwHh
"""



"""## **HELLO**

# ADDITION
"""

num1 = 5;
num2 = 7;
print("num1 + num2 = ", 5+7);

"""# SUBTRACTION"""

num1 = 5;
num2 = 7;
print("num1 + num2 = ", 5-7);

"""# MULTIPLICATION"""

num1 = 5;
num2 = 7;
print("num1 + num2 = ", 5*7);

"""# DIVISION"""

num1 = 5;
num2 = 7;
print("num1 + num2 = ", 5/7);