# -*- coding: utf-8 -*-
"""RepResult_KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Muzswiapm8-5GWbiDOLQxBZhaJajH3B-
"""

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

"""# **STEP 1: LOAD DATASET**"""

data = load_iris()  # Load the Iris Dataset
x = data.data        # Feature (input)
y = data.target     # Labels (outputs)

"""# **STEP 2: Split data into Training and testing sets (80% train, 20% test)**"""

x_train, X_test, y_Train, y_test = train_test_split(
    x,y,test_size=0.2,random_state=42
)

"""# **STEP 3: Create KNN model with K = 3**"""

model = KNeighborsClassifier(n_neighbors=20)

"""# **STEP 4: Train the Model**"""

model.fit(x_train,y_Train)

"""# **STEP 5: Predict on both training and test data**"""

y_tain_pred = model.predict(x_train)
y_test_pred = model.predict(X_test)

"""# **STEP 6: EVAluate accuracy for both**"""

train_accuracy = accuracy_score(y_Train,y_tain_pred)
test_accuracy = accuracy_score(y_test,y_test_pred)

"""# **STEP 7: Print the results**"""

print("Training Accuracy: ", train_accuracy)
print("Testing Accuracy: ", test_accuracy)