# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXTOYXYfTmZPnoD2p0Q9d3lYbgr7saQr

# **Numpy**
"""

import numpy as np

# Create 1D array
arr = np.arange(5, 25)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(25, 45)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)