# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NXTOYXYfTmZPnoD2p0Q9d3lYbgr7saQr

# **Numpy**
"""

import numpy as np

# Create 1D array
arr = np.arange(5, 25)
print('1D Array:', arr)

# Reshape to 4x5 matrix
matrix = arr.reshape(4, 5)
print('4x5 Matrix:\n', matrix)

# Mean, Median, Std
print('Mean:', np.mean(arr))
print('Median:', np.median(arr))
print('Standard Deviation:', np.std(arr))

# Element-wise operations
arr2 = np.arange(25, 45)
print('Addition:', arr + arr2)
print('Multiplication:', arr * arr2)

"""# **Matplotlib**"""

import matplotlib.pyplot as plt

# Line Plot
x = list(range(1, 15))
y = [i**2 for i in x]
plt.plot(x, y)
plt.title('Numbers vs Squares')
plt.xlabel('Numbers')
plt.ylabel('Squares')
plt.show()

# Bar Chart
students = ['Hifza', 'Sara', 'Tahir', 'Zara', 'Memoona', 'Ayesha']
marks = [85, 90, 78, 92, 88, 95]
plt.bar(students, marks)
plt.title('Student Marks')
plt.xlabel('Students')
plt.ylabel('Marks')
plt.show()

# Pie Chart
categories = ['Category A', 'Category B', 'Category C', 'Category D']
values = [25, 40, 15, 20]
plt.pie(values, labels=categories, autopct='%1.1f%%')
plt.title('Category Distribution')
plt.show()