# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pCd8TjiUov_02-9UQkdcBc96gSrNU6vf

# **TASK 1: Tree and Graph using BFS, DFS**
"""

# TREE Example: BFS and DFS using numbers

tree = {
    1: [2, 3],
    2: [4, 5],
    3: [6, 7],
    4: [],
    5: [],
    6: [],
    7: []
}

# Breadth First Search (BFS)
def bfs_tree(start):
    visited = []
    queue = [start]

    while queue:
        node = queue.pop(0)
        if node not in visited:
            visited.append(node)
            queue.extend(tree[node])
    return visited

# Depth First Search (DFS)
def dfs_tree(start, visited=None):
    if visited is None:
        visited = []
    visited.append(start)
    for neighbor in tree[start]:
        if neighbor not in visited:
            dfs_tree(neighbor, visited)
    return visited

print("BFS (Tree):", bfs_tree(1))
print("DFS (Tree):", dfs_tree(1))

# GRAPH Example: BFS and DFS using numbers

graph = {
    1: [2, 3],
    2: [1, 3, 4],
    3: [1, 2, 5],
    4: [2, 5],
    5: [3, 4]
}

# Breadth First Search (BFS)
def bfs_graph(start):
    visited = []
    queue = [start]

    while queue:
        node = queue.pop(0)
        if node not in visited:
            visited.append(node)
            queue.extend(graph[node])
    return visited

# Depth First Search (DFS)
def dfs_graph(start, visited=None):
    if visited is None:
        visited = []
    visited.append(start)
    for neighbor in graph[start]:
        if neighbor not in visited:
            dfs_graph(neighbor, visited)
    return visited

print("BFS (Graph):", bfs_graph(1))
print("DFS (Graph):",dfs_graph(1))

"""# **TASK 2: Dictionary Operations**"""

# TASK 2: Dictionary Operations

student = {
    "name": "HIFZA",
    "age": 20,
    "roll_number": "CS101",
    "grade": "B"
}

# Print all keys and values
print("Original Dictionary:", student)

# Update the grade
student["grade"] = "A"

# Add a new key-value pair (email)
student["email"] = "Hifza@example.com"

# Delete roll_number key
del student["roll_number"]

print("Updated Dictionary:",student)

"""# **TASK 3: Simple Line Plot**"""

# TASK 3: Simple Line Plot

import matplotlib.pyplot as plt

X = [1, 2, 3, 4, 5]
Y = [2, 4, 6, 8, 10]

plt.plot(X, Y, marker='o')
plt.title("Simple Line Plot")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.grid(True)
plt.show()

"""# **TASK 4: Water Jug Problem using BFS and DFS**

"""

# TASK 5: Water Jug Problem using BFS and DFS

import time
import tracemalloc
from collections import deque

max_x, max_y, goal = 4, 3, 2

def get_successors(state):
    x, y = state
    successors = set()
    successors.add((max_x, y))  # Fill X
    successors.add((x, max_y))  # Fill Y
    successors.add((0, y))      # Empty X
    successors.add((x, 0))      # Empty Y
    pour = min(x, max_y - y)    # Pour X → Y
    successors.add((x - pour, y + pour))
    pour = min(y, max_x - x)    # Pour Y → X
    successors.add((x + pour, y - pour))
    return successors

def bfs():
    start = (0, 0)
    visited = set()
    queue = deque([(start, [start])])
    while queue:
        (x, y), path = queue.popleft()
        if x == goal or y == goal:
            return path
        visited.add((x, y))
        for s in get_successors((x, y)):
            if s not in visited:
                queue.append((s, path + [s]))
    return None

def dfs():
    start = (0, 0)
    visited = set()
    stack = [(start, [start])]
    while stack:
        (x, y), path = stack.pop()
        if x == goal or y == goal:
            return path
        visited.add((x, y))
        for s in get_successors((x, y)):
            if s not in visited:
                stack.append((s, path + [s]))
    return None

# Measure BFS
tracemalloc.start()
start_time = time.time()
bfs_path = bfs()
bfs_time = time.time() - start_time
bfs_mem = tracemalloc.get_traced_memory()[1] / 1024
tracemalloc.stop()

# Measure DFS
tracemalloc.start()
start_time = time.time()
dfs_path = dfs()
dfs_time = time.time() - start_time
dfs_mem = tracemalloc.get_traced_memory()[1] / 1024
tracemalloc.stop()

print("=== BFS Results ===")
print("Path:", bfs_path)
print("Steps:", len(bfs_path))
print(f"Time Taken: {bfs_time:.6f} sec")
print(f"Memory Used: {bfs_mem:.2f} KB\n")

print("=== DFS Results ===")
print("Path:", dfs_path)
print("Steps:", len(dfs_path))
print(f"Time Taken: {dfs_time:.6f} sec")
print(f"Memory Used: {dfs_mem:.2f} KB")

"""# Task: 5 A* Search to find Resultant path"""

# A* on the provided 6x6 maze (4-neighbour moves)
import heapq

walls = {(1,0),(1,1),(3,1),(4,1),(5,1),(2,3),(3,2),(4,4),(0,5),(1,5),(3,5)}
letters = {
    (0,0):'A', (1,0):None, (2,0):'B', (3,0):'C', (4,0):'D', (5,0):'E',
    (0,1):'F', (1,1):None, (2,1):'G', (3,1):None, (4,1):None, (5,1):None,
    (0,2):'H', (1,2):'I', (2,2):'J', (3,2):None, (4,2):'K', (5,2):'L',
    (0,3):'M', (1,3):'N', (2,3):None, (3,3):'O', (4,3):'P', (5,3):'Q',
    (0,4):'R', (1,4):'S', (2,4):'T', (3,4):'U', (4,4):None, (5,4):'V',
    (0,5):None,(1,5):None,(2,5):'W',(3,5):None,(4,5):'X',(5,5):'Y'
}
start = (0,0)
goal = (5,5)
width, height = 6,6

def heuristic(a,b):
    return abs(a[0]-b[0]) + abs(a[1]-b[1])

def neighbors(node):
    x,y = node
    for dx,dy in [(1,0),(-1,0),(0,1),(0,-1)]:
        nx,ny = x+dx, y+dy
        if 0 <= nx < width and 0 <= ny < height and (nx,ny) not in walls:
            yield (nx,ny)

def a_star(start, goal):
    open_set = []
    heapq.heappush(open_set, (heuristic(start,goal), 0, start))
    came_from = {}
    g_score = {start: 0}
    closed = set()
    while open_set:
        f, g, current = heapq.heappop(open_set)
        if current == goal:
            path = []
            node = current
            while node in came_from:
                path.append(node)
                node = came_from[node]
            path.append(start)
            path.reverse()
            return path
        if current in closed:
            continue
        closed.add(current)
        for nb in neighbors(current):
            tentative_g = g_score[current] + 1
            if tentative_g < g_score.get(nb, 1e9):
                came_from[nb] = current
                g_score[nb] = tentative_g
                heapq.heappush(open_set, (tentative_g + heuristic(nb, goal), tentative_g, nb))
    return None

path = a_star(start, goal)
path_letters = [letters.get(p, '?') if letters.get(p, None) is not None else f"({p[0]},{p[1]})" for p in path] if path else None

print("Path (coords):", path)
print("Path (letters):", " -> ".join(path_letters))